version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: easeinv-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - easeinv_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: easeinv
      TZ: UTC
      PGTZ: UTC

  rabbitmq:
    image: rabbitmq:3-management
    container_name: easeinv-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: easeinv-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  easeinv_postgres:
  rabbitmq_data:
  elasticsearch_data:
