version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: easeinv-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - easeinv_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: easeinv

  rabbitmq:
    image: rabbitmq:3-management
    container_name: easeinv-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  easeinv_postgres:
  rabbitmq_data:
