export enum NotificationType {
  // Billing
  INVOICE_CREATED = "INVOICE_CREATED",
  INVOICE_PAID = "INVOICE_PAID",
  INVOICE_OVERDUE = "INVOICE_OVERDUE",

  // Inventory
  STOCK_LOW = "STOCK_LOW",
  STOCK_OUT = "STOCK_OUT",

  // Store team
  STORE_USER_INVITED = "STORE_USER_INVITED",
  STORE_USER_JOINED = "STORE_USER_JOINED",
  STORE_USER_ROLE_CHANGED = "STORE_USER_ROLE_CHANGED",

  // Auth
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  // Generic
  GENERAL = "GENERAL",
}
