version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: easeinv-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: easeinv
      RABBITMQ_DEFAULT_PASS: qwbtre*i184r
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: easeinv-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  rabbitmq_data:
  elasticsearch_data:
