upstream backend {
    server 127.0.0.1:4000;
}

upstream frontend {
	server 172.31.33.72:3000;
}

server {
    listen 80;
    server_name easeinv.app www.easeinv.app api.easeinv.app;

    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name easeinv.app www.easeinv.app;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    # GZIP Compression
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;
    gzip_types application/json application/javascript text/plain text/css application/xml text/xml;


    location /backend/ {
        proxy_pass http://backend;
        # ensure upstream doesn't already compress
    	proxy_set_header Accept-Encoding "";
    	include proxy_params;
    }

    location / {
        proxy_pass http://frontend;

        # ensure upstream doesn't already compress
    	proxy_set_header Accept-Encoding "";

        include proxy_params;
    }

    error_page 497 https://$host:$server_port$request_uri;

}

server {
    listen 443 ssl;
    server_name api.easeinv.app;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    # GZIP Compression
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;
    gzip_types application/json application/javascript text/plain text/css application/xml text/xml;


    location / {
        proxy_pass http://backend;
        # ensure upstream doesn't already compress
    	proxy_set_header Accept-Encoding "";
    	include proxy_params;
    }

    error_page 497 https://$host:$server_port$request_uri;

}
