upstream backend {
    server 127.0.0.1:4000;
}

upstream frontend {
    server frontend.easeinv.app;
}

server {
    listen 80;
    server_name easeinv.app www.easeinv.app api.easeinv.app;

    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name easeinv.app www.easeinv.app;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    # GZIP Compression
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;
    gzip_types application/json application/javascript text/plain text/css application/xml text/xml;


    location /backend/ {
        proxy_pass http://backend;
        # ensure upstream doesn't already compress
    	proxy_set_header Accept-Encoding "";
    	include proxy_params;
    }

    location / {
        proxy_pass https://frontend.easeinv.app;

        proxy_ssl_server_name on;
        proxy_ssl_name frontend.easeinv.app;

        # IMPORTANT: send Vercel the upstream hostname
        proxy_set_header Host frontend.easeinv.app;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Accept-Encoding "";
    }

    error_page 497 https://$host:$server_port$request_uri;

}

server {
    listen 443 ssl;
    server_name api.easeinv.app;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    # GZIP Compression
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;
    gzip_types application/json application/javascript text/plain text/css application/xml text/xml;


    location / {
        proxy_pass http://backend;
        # ensure upstream doesn't already compress
    	proxy_set_header Accept-Encoding "";
    	include proxy_params;
    }

    error_page 497 https://$host:$server_port$request_uri;

}
